name: iptv-m3u-maker
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 2 * * *'
    
jobs:
  run-python-script:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.10'
      - name: Update IPTV Files
        run: |
          pip install requests
          python python/iptv.py
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add tv.json tv.m3u
          git commit -m "IPTV M3U File Automatic Update."
      - name: Push changes
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
