name: iptv-m3u-maker
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 2 * * *'
    
jobs:
  run-python-script:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7.10'
      - run: pip install requests
      - run: python python/iptv.py
